name: flutter_native_image_example
description: Demonstrates how to use the flutter_native_image plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_image:
    path: ../

flutter:
  uses-material-design: true
